// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiclesPriceListApp.Infrastructure.Data;

namespace VehiclesPriceListRestApi.Migrations
{
    [DbContext(typeof(VehiclesPriceListAppContext))]
    partial class VehiclesPriceListAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("VehiclesPriceListApp.Core.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VehiclesPriceListApp.Core.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("PasswordHash");

                    b.Property<int?>("RoleId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehiclesPriceListApp.Core.Entity.VehicleMenufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VehicleMenufacturer");
                });

            modelBuilder.Entity("VehiclesPriceListApp.Core.Entity.VehicleMenufacturingOrigin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VehicleMenufacturingOrigin");
                });

            modelBuilder.Entity("VehiclesPriceListApp.Core.Entity.VehicleOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Telephone");

                    b.HasKey("Id");

                    b.ToTable("VehicleOwner");
                });

            modelBuilder.Entity("VehiclesPriceListApp.Core.Entity.VehiclePriceListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AskingPrice");

                    b.Property<string>("Color");

                    b.Property<DateTime>("DateReceived");

                    b.Property<string>("EngineType");

                    b.Property<string>("EquippingDetails");

                    b.Property<DateTime>("TestValidExpiration");

                    b.Property<int>("VehicleMenufacturerId");

                    b.Property<int>("VehicleMenufacturingOriginId");

                    b.Property<int>("VehicleOwnerId");

                    b.Property<int>("VehicleStatusId");

                    b.Property<int>("VehicleTypeId");

                    b.HasKey("Id");

                    b.HasIndex("VehicleMenufacturerId");

                    b.HasIndex("VehicleMenufacturingOriginId");

                    b.HasIndex("VehicleOwnerId");

                    b.HasIndex("VehicleStatusId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehiclePriceListItem");
                });

            modelBuilder.Entity("VehiclesPriceListApp.Core.Entity.VehicleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VehicleStatus");
                });

            modelBuilder.Entity("VehiclesPriceListApp.Core.Entity.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VehicleType");
                });

            modelBuilder.Entity("VehiclesPriceListApp.Core.Entity.User", b =>
                {
                    b.HasOne("VehiclesPriceListApp.Core.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("VehiclesPriceListApp.Core.Entity.VehiclePriceListItem", b =>
                {
                    b.HasOne("VehiclesPriceListApp.Core.Entity.VehicleMenufacturer", "VehicleMenufacturer")
                        .WithMany("VehiclePriceListItem")
                        .HasForeignKey("VehicleMenufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VehiclesPriceListApp.Core.Entity.VehicleMenufacturingOrigin", "VehicleMenufacturingOrigin")
                        .WithMany("VehiclePriceListItem")
                        .HasForeignKey("VehicleMenufacturingOriginId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VehiclesPriceListApp.Core.Entity.VehicleOwner", "VehicleOwner")
                        .WithMany("VehiclePriceListItem")
                        .HasForeignKey("VehicleOwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VehiclesPriceListApp.Core.Entity.VehicleStatus", "VehicleStatus")
                        .WithMany("VehiclePriceListItem")
                        .HasForeignKey("VehicleStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VehiclesPriceListApp.Core.Entity.VehicleType", "VehicleType")
                        .WithMany("VehiclePriceListItem")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
